### ISSUE TITLE
How to change tooltip background-color?

### ISSUE THREAD

**Issue by jyotiarora2610** [tvkhoa/react-tippy#78]
By using tooltip theme, there are only three options "dark,light and transparent". But i want to give a custom theme to my tooltip. Please give any suggestion.

**Comment by virmelcruz** [comment]
I did it by overriding the default styles. something like this:

```
.tippy-tooltip {
  background-color: #DBEEF5;
  border-radius: 25px;
  color: black;
}

//if you have arrow
.tippy-popper[x-placement^=top] [x-arrow] {
  border-top: 7px solid #DBEEF5;
}
```

**Comment by glenngijsberts** [comment]
Any updates on this? Still unable to change any styles whatsoever. Pretty inconvenient..

**Comment by phamtuan2993** [comment]
Thanks @virmelcruz for your reaction on the question.

@jyotiarora2610  and @glenngijsberts , Sorry for this late reply, have you tried with suggestion on changing global style, you can have more details on this https://github.com/tvkhoa/react-tippy/issues/3#issuecomment-297688807

Thanks

**Comment by felpin** [comment]
You can create a [custom theme](https://atomiks.github.io/tippyjs/themes/#creating-a-theme), like:
```css
.tippy-tooltip.tomato-theme {
  background-color: tomato;
  color: yellow;
}

.tippy-tooltip.tomato-theme[data-animatefill] {
  background-color: transparent;
}

.tippy-tooltip.tomato-theme .tippy-backdrop {
  background-color: tomato;
}
```

And then on your `Tooltip` component, use `theme="tomato"`
