### ISSUE TITLE
How is the instant example can be triggered?

### ISSUE THREAD

**Issue by ReactGirl** [tvkhoa/react-tippy#92]
IM getting delay to have the popup to disappear

**Comment by KubaJastrz** [comment]
I found out that you need to explicitly reset `transition-duration`. 
```jsx
<Tooltip
    animation="none"
    animateFill={false}
>
```
```css
.tippy-tooltip, .tippy-popper {
    transition-duration: 0s !important;
}
```
